#!/usr/bin/env python

import os,sys;
print("build android compile env...")

cmd = "sudo apt-get update"
os.system(cmd)
cmd = "sudo apt-get install openjdk-8-jdk"
os.system(cmd)
cmd = "sudo apt-get install git-core gnupg flex bison gperf build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc unzip"
os.system(cmd)

print("----Successful---")
